### ISSUE TITLE
error: syntax error, unexpected '(', expecting '|'

### ISSUE THREAD

**Issue by ubuntuguruwannabe** [adihrustic/Mullvad-WireGuard-Wrapper#3]
Hi,

I'm currently trying to install the script on Ubuntu 16.04 Server but I encounter the following error:

[+] Contacting Mullvad API for server locations.
error: syntax error, unexpected '(', expecting '|'
foreach .countries[] as $country (.; .; foreach $country.cities[] as $city (.; .; foreach $city.relays[] as $relay (.; .; $country.name, $city.name, $relay.hostname, $relay.public_key, $relay.ipv4_addr_in)))
                                 ^
1 compile error
[-] Error: Unable to parse response.

Please help me out if you can. Thank you.

**Comment by adihrustic** [comment]
This comes from Mullvad's own installation script which I didn't write. Did you install all the dependencies before trying to update the server list? If so, I would advise emailing Mullvad directly.
